### ISSUE TITLE
Erreur de minification de markup

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#131]
Cela n'est pas bloquant.

```
Copying '/home/travis/build/AlexandreDecan/Lexpage/app/commons/static/js/markup.js'
[ERROR] in /tmp/tmprzs9vvh6.js
  241:35:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  249:38:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  262:38:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  269:29:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  281:41:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  283:43:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  293:36:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  294:35:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  308:39:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  316:32:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  317:31:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  327:40:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  336:35:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  344:32:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  345:31:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  349:35:invalid property id
[ERROR] in /tmp/tmprzs9vvh6.js
  1:0:Compilation produced 16 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 16 syntax errors.
    at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
    at org.mozilla.javascript.Parser.parse(Parser.java:396)
    at org.mozilla.javascript.Parser.parse(Parser.java:340)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
    at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
ERROR:root:Minify js error for js/markup.js
Traceback (most recent call last):
  File "/home/travis/build/AlexandreDecan/Lexpage/app/minify.py", line 34, in _save
    assert yuicompress == 0, 'YUI Compressor failed on %s' % name
AssertionError: YUI Compressor failed on js/markup.js
```

**Comment by AlexandreDecan** [comment]
Je regarderai d'où vient l'erreur, sans doute que le JS est mal formé quelque part.
